---
--- Generated by Luanalysis
--- Created by 王雨萌.
--- DateTime: 2023/3/21 11:55
---
local key = KEYS[1]; -- 锁的key
local threadId = ARGV[1];  --线程唯一标识
local releaseTime = ARGV[2]; -- 锁的自动释放时间
-- 判断锁是否存在
if(redis.call('exists',key)  == 0) then
    --不存在 获取锁
    redis.call('hset',key,threadId,'1');
    -- 设置有效期
    redis.call('expire',key,releaseTime);
    return  1;-- 返回结果
end;

-- 锁已存在  判断threadId是否是自己
if(redis.call('hexists',key,threadId) == 1) then
    -- 重载次数加一
    redis.call('hincrby',key,threadId,'1');
    redis.call('expire',key,releaseTime);
    return 1;
end
return 0; -- 获取失败
