---
--- Generated by Luanalysis
--- Created by 王雨萌.
--- DateTime: 2023/3/22 11:02
---
-- 参数列表
-- 1.优惠券id
local voucherId = ARGV[1];
-- 2.用户id
local userId = ARGV[2];

--- 2.数据key
-- 2.1. 库存key
local stockKey = 'seckill:stock:'  .. voucherId
-- 2.2 订单key
local orderkKey = 'seckill:order:'  .. voucherId

-- 3. 脚本业务
-- 3.1 判断库存是否充足‘
if(tonumber(redis.call('get',stockKey))<=0) then
    -- 库存不足 返回1
    return 1;
end
-- 判断当前用户是否下单
if(redis.call('sismember',orderkKey,userId) == 1)then
    return 2;
end
-- 扣减库存
redis.call('incrby',stockKey,-1);
-- 完成下单
redis.call('sadd',orderkKey,userId)
return 0;