---
--- Generated by Luanalysis
--- Created by 王雨萌.
--- DateTime: 2023/3/21 12:04
---
local key = KEYS[1]; -- 锁的key
local threadId = ARGV[1];  --线程唯一标识
local releaseTime = ARGV[2]; -- 锁的自动释放时间
-- 判断当前锁是否还被自己持有
if(redis.call('hexists',key,threadId) == 0) then
    return nil; -- 不持有 直接返回
end
-- 是自己的锁 重入次数-1
local count = redis.call('hincrby', key, threadId, -1)
-- 判断重入次数是否已经为0
if(count > 0 ) then
    -- 重新设置有效期
    redis.call("expire",key,threadId,releaseTime);
    return nil;
else
    redis.call('del',key);
    return nil;
end